platform :ios, '17.0'

target 'WordQuizDaily' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WordQuizDaily

end

target 'WordQuizWidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WordQuizWidgetExtension

end
